In [7]:
import pandas as pd
import numpy as np

test = pd.read_csv('lazada_test.csv')
train = pd.read_csv('lazada_train.csv')

In [8]:
test.head()

,data_id,label,is_treat,f0,f1,f2,f3,f4,f5,f6,...,f73,f74,f75,f76,f77,f78,f79,f80,f81,f82
0,test_0,0,1,2,6,6,3.663562,5.500000,0.0,1.380211,...,0.0,1.0,1.0,0.0,1.0,0.0,-0.016784,0.013613,0.022173,0.016554
1,test_1,0,0,2,2,2,3.583519,9.250000,0.0,0.301030,...,0.0,1.0,1.0,0.0,1.0,0.0,-0.016784,0.013613,0.022173,0.016554
2,test_2,0,0,2,44,44,1.098612,2.500000,0.0,0.301030,...,0.0,1.0,1.0,0.0,1.0,0.0,-0.016784,0.013613,0.022173,0.016554
3,test_3,0,1,2,365,365,0.000000,1.000000,0.0,0.000000,...,0.0,1.0,1.0,0.0,1.0,0.0,-0.016784,0.013613,0.022173,0.016554
4,test_4,0,0,4,69,69,0.693147,1.666667,0.0,0.602060,...,0.0,1.0,1.0,0.0,1.0,0.0,-0.016784,0.013613,0.022173,0.016554

In [9]:
train_data.head(5)

,data_id,label,is_treat,f0,f1,f2,f3,f4,f5,f6,...,f73,f74,f75,f76,f77,f78,f79,f80,f81,f82
0,train_0,0,0,0,365,365,0.000000,0.000000,0.000000,0.000000,...,0.0,1.0,0.0,1.0,1.0,0.0,0.169175,0.045724,0.081805,0.07619
1,train_1,0,1,2,36,36,4.174387,9.666667,2.197225,1.477121,...,0.0,1.0,1.0,0.0,1.0,0.0,0.169175,0.045724,0.081805,0.07619
2,train_2,0,0,3,276,276,0.000000,1.000000,0.000000,0.000000,...,0.0,1.0,1.0,0.0,1.0,0.0,0.169175,0.045724,0.081805,0.07619
3,train_3,0,1,0,39,39,0.000000,0.000000,0.000000,0.000000,...,0.0,1.0,1.0,0.0,1.0,0.0,0.169175,0.045724,0.081805,0.07619
4,train_4,0,1,0,308,308,0.000000,0.000000,0.000000,0.000000,...,0.0,1.0,1.0,0.0,1.0,0.0,0.169175,0.045724,0.081805,0.07619

In [10]:
print("Train shape:", train.shape)
print("Test shape:", test.shape)

Train shape: (926669, 86)
Test shape: (181669, 86)

In [11]:
print(train.columns.tolist())
print(train.head())

['data_id', 'label', 'is_treat', 'f0', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10', 'f11', 'f12', 'f13', 'f14', 'f15', 'f16', 'f17', 'f18', 'f19', 'f20', 'f21', 'f22', 'f23', 'f24', 'f25', 'f26', 'f27', 'f28', 'f29', 'f30', 'f31', 'f32', 'f33', 'f34', 'f35', 'f36', 'f37', 'f38', 'f39', 'f40', 'f41', 'f42', 'f43', 'f44', 'f45', 'f46', 'f47', 'f48', 'f49', 'f50', 'f51', 'f52', 'f53', 'f54', 'f55', 'f56', 'f57', 'f58', 'f59', 'f60', 'f61', 'f62', 'f63', 'f64', 'f65', 'f66', 'f67', 'f68', 'f69', 'f70', 'f71', 'f72', 'f73', 'f74', 'f75', 'f76', 'f77', 'f78', 'f79', 'f80', 'f81', 'f82']
   data_id  label  is_treat  f0   f1   f2        f3        f4        f5  \
0  train_0      0         0   0  365  365  0.000000  0.000000  0.000000
1  train_1      0         1   2   36   36  4.174387  9.666667  2.197225
2  train_2      0         0   3  276  276  0.000000  1.000000  0.000000
3  train_3      0         1   0   39   39  0.000000  0.000000  0.000000
4  train_4      0         1   0  308  308  0.000000  0.000000  0.000000

         f6  ...  f73  f74  f75  f76  f77  f78       f79       f80       f81  \
0  0.000000  ...  0.0  1.0  0.0  1.0  1.0  0.0  0.169175  0.045724  0.081805
1  1.477121  ...  0.0  1.0  1.0  0.0  1.0  0.0  0.169175  0.045724  0.081805
2  0.000000  ...  0.0  1.0  1.0  0.0  1.0  0.0  0.169175  0.045724  0.081805
3  0.000000  ...  0.0  1.0  1.0  0.0  1.0  0.0  0.169175  0.045724  0.081805
4  0.000000  ...  0.0  1.0  1.0  0.0  1.0  0.0  0.169175  0.045724  0.081805

       f82
0  0.07619
1  0.07619
2  0.07619
3  0.07619
4  0.07619

[5 rows x 86 columns]

In [12]:
feature_cols = [f"f{i}" for i in range(83)]

print("Số features:", len(feature_cols))
print("Thiếu features:", set(feature_cols) - set(train.columns))

Số features: 83
Thiếu features: set()

In [14]:
print("Tổng số dòng:", len(train))

print("\nSố lượng label:")
print(train["label"].value_counts())

print("\nTỷ lệ label:")
print(
    train["label"]
    .value_counts(normalize=True)
    .mul(100)
    .round(4)
)

print("\nLabel theo treatment:")
print(
    pd.crosstab(
        train["is_treat"],
        train["label"],
        margins=True
    )
)

print("\nPositive rate theo treatment:")
print(
    train.groupby("is_treat")["label"]
    .agg(["count", "sum", "mean"])
)

Tổng số dòng: 926669

Số lượng label:
label
0    908221
1     18448
Name: count, dtype: int64

Tỷ lệ label:
label
0    98.0092
1     1.9908
Name: proportion, dtype: float64

Label theo treatment:
label          0      1     All
is_treat
0         714379   6810  721189
1         193842  11638  205480
All       908221  18448  926669

Positive rate theo treatment:
           count    sum      mean
is_treat
0         721189   6810  0.009443
1         205480  11638  0.056638